PREFIX cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cim: <http://iec.ch/TC57/2013/CIM-schema-cim16#>

SELECT *
WHERE {
  ?path rdf:type rdf:Property ;
        rdfs:domain ?class ;
        cims:multiplicity ?cardinality .
  OPTIONAL { ?path rdfs:range ?range }
  OPTIONAL { ?path cims:dataType ?datatype }
}